# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

# 自作ライブラリの場所
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------

project = 'myapi'
copyright = '2023, Osamu NAKAJIMA'
author = 'Osamu NAKAJIMA'

# The full version, including alpha/beta/rc tags
release = '1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
                'sphinx.ext.viewcode', # ソースコードへのリンクがつく
                'sphinx.ext.autodoc', # ソースコードから自動でrstを作成するコア
                'sphinx.ext.autosummary', #ソースコードから自動でrstを作成
                'sphinx.ext.napoleon', # Google, Numpy スタイルのdocstirng　解釈
                'sphinx_autodoc_typehints', # docstringの型を定義から自動で書いてくれる
                'sphinx.ext.intersphinx',  # 他のプロジェクトのドキュメント参照
                'sphinx_copybutton', # 各セルにコピーボタンが設けられる
                'nbsphinx', # jupyternotebookをドキュメントに含める
                'IPython.sphinxext.ipython_console_highlighting', # nbsphinxに付随して追加する
                'sphinx_sitemap', # sitemap.xmlの自動生成
]

# intersphinx_mapping(以下は標準ライブラリとpandasの参照がある場合)
intersphinx_mapping = {
                "python": ("https://docs.python.org/3/", None),
                'python': ('https://pandas.pydata.org/docs/', None)
}

# autosummary_generate（autosummaryの有効化）
autosummary_generate = True

# 名前空間を class/method や signatures から除く
add_module_names = False 

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
# exclude_patterns（jupyterで作業すると自動でできる隠しファイルが鬱陶しいので除外）
exclude_patterns = ['*/.ipynb_checkpoints/*', '.ipynb_checkpoints/*']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme(変えたい場合は設定、themeのインストールは別途必要)
html_theme = 'furo'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_baseurl = 'http://localhost:8080/apidoc/'